package com.amazon.market.entity;
// Generated Apr 12, 2018 5:40:29 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeliverypersonZone generated by hbm2java
 */
@Entity
@Table(name = "Deliveryperson_Zone")
public class DeliverypersonZone implements java.io.Serializable {

	

	private Integer id;
	private int userid;
	private int zoneid;

	public DeliverypersonZone() {
	}

	public DeliverypersonZone(int userid, int zoneid) {
		this.userid = userid;
		this.zoneid = zoneid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "Zoneid", nullable = false)
	public int getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(int zoneid) {
		this.zoneid = zoneid;
	}

	@Override
	public String toString() {
		return "DeliverypersonZone [id=" + id + ", userid=" + userid + ", zoneid=" + zoneid + "]";
	}
}
