package com.amazon.market.entity;
// Generated Apr 12, 2018 5:40:29 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationZones generated by hbm2java
 */
@Entity
@Table(name = "Location_Zones")
public class LocationZones implements java.io.Serializable {

	private int id;
	private String locationName;
	private int zoneid;
	private Date lastupdated;

	public LocationZones() {
	}

	public LocationZones(int id, String locationName, int zoneid) {
		this.id = id;
		this.locationName = locationName;
		this.zoneid = zoneid;
	}

	public LocationZones(int id, String locationName, int zoneid, Date lastupdated) {
		this.id = id;
		this.locationName = locationName;
		this.zoneid = zoneid;
		this.lastupdated = lastupdated;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Location_Name", nullable = false, length = 30)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "Zoneid", nullable = false)
	public int getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(int zoneid) {
		this.zoneid = zoneid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Lastupdated", length = 19)
	public Date getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

}
