package com.amazon.market.entity;

// Generated Apr 12, 2018 5:40:29 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "Order_Status")
public class OrderStatus implements java.io.Serializable {

	

	private Integer id;
	private String orderStatus;
	private String systemStatus;

	public OrderStatus() {
	}

	public OrderStatus(String orderStatus, String systemStatus) {
		this.orderStatus = orderStatus;
		this.systemStatus = systemStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Order_Status", nullable = false, length = 20)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "System_Status", nullable = false, length = 20)
	public String getSystemStatus() {
		return this.systemStatus;
	}

	public void setSystemStatus(String systemStatus) {
		this.systemStatus = systemStatus;
	}
	
	@Override
	public String toString() {
		return "OrderStatus [id=" + id + ", orderStatus=" + orderStatus + ", systemStatus=" + systemStatus + "]";
	}

}
