package com.amazon.market.entity;
// Generated Apr 12, 2018 5:40:29 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SellerRating generated by hbm2java
 */
@Entity
@Table(name = "Seller_Rating")
public class SellerRating implements java.io.Serializable {

	private Integer id;
	private int sellerid;
	private int userid;
	private int rating;
	private int orderid;
	private int productid;

	public SellerRating() {
	}

	public SellerRating(int orderid, int productid,int sellerid, int userid, int rating) {
		this.sellerid = sellerid;
		this.userid = userid;
		this.rating = rating;
		this.orderid = orderid;
		this.productid = productid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "Orderid", nullable = false)
	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}
	
	@Column(name = "Productid", nullable = false)
	public int getProductid() {
		return this.productid;
	}

	

	public void setProductid(int productid) {
		this.productid = productid;
	}

	@Column(name = "Sellerid", nullable = false)
	public int getSellerid() {
		return this.sellerid;
	}

	public void setSellerid(int sellerid) {
		this.sellerid = sellerid;
	}

	@Column(name = "Userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "Rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Override
	public String toString() {
		return "SellerRating [id=" + id + ", sellerid=" + sellerid + ", userid=" + userid + ", rating=" + rating
				+ ", orderid=" + orderid + ", productid=" + productid + "]";
	}
}
