
// Generated Apr 12, 2018 5:40:29 PM by Hibernate Tools 5.2.8.Final
package com.amazon.market.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "User_Address", catalog = "marche")
public class UserAddress implements java.io.Serializable {

	private int id;
	private int userid;
	private String firstname;
	private String lastname;
	private String doorno;
	private String street;
	private int area;
	private String city;
	private String state;
	private int pincode;
	private boolean isDefault;
	private int addressType;

	public UserAddress() {
	}

	public UserAddress(int userid, String firstname, String lastname, String doorno, String street, int area,
			String city, String state, int pincode) {
		this.userid = userid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.doorno = doorno;
		this.street = street;
		this.area = area;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "Firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "Lastname", nullable = false, length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "Doorno", nullable = false, length = 20)
	public String getDoorno() {
		return this.doorno;
	}

	public void setDoorno(String doorno) {
		this.doorno = doorno;
	}

	@Column(name = "Street", nullable = false, length = 20)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "Area", nullable = false)
	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	@Column(name = "City", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false, length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Pincode", nullable = false)
	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	@Column(name = "Is_Default", nullable = false)
	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

	@Column(name = "Address_Type", nullable = false)
	public int getAddressType() {
		return this.addressType;
	}

	public void setAddressType(int addressType) {
		this.addressType = addressType;
	}

}
